//! Blender round-trip fidelity.
//!
//! Fixtures under `tests/fixtures/` come in three flavours per model:
//!   `<name>.glb`          — Hew's own export (the source of truth)
//!   `<name>.blender.glb`  — that file opened and re-saved by Blender, no edits
//!   `<name>.edited.glb`   — opened in Blender, one object moved/rotated+applied
//! The `.blender`/`.edited` variants are regenerated by
//! `scripts/blender_roundtrip.py` (needs Blender + numpy); they are committed so
//! this test runs in CI without Blender.
//!
//! The contract is *fidelity*: re-importing the Blender output reconstructs the
//! same number of editable, watertight Objects (and materials/textures) as the
//! original Hew export. What is NOT preserved — shared component/instance
//! structure — is documented in `docs/INTEROP.md` and asserted below so the
//! gap is pinned, not silently drifting.

use kernel::Document;
use std::path::Path;

#[derive(PartialEq, Eq, Debug)]
struct Summary {
    objects: usize,
    watertight: usize,
    leaky: usize,
    skipped: usize,
    materials: usize,
    textured: usize,
    shared_defs: usize,
    textures_missing: usize,
}

fn import_summary(rel: &str) -> Summary {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(rel);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {rel}: {e}"));
    let (scene, missing) =
        gltf_import::import(&bytes).unwrap_or_else(|e| panic!("import {rel}: {e}"));
    let materials = scene.materials.len();
    let textured = scene
        .materials
        .iter()
        .filter(|m| m.texture.is_some())
        .count();
    let shared_defs = scene.defs.len();
    let mut doc = Document::new();
    let (report, _) = doc
        .ingest(scene, missing)
        .unwrap_or_else(|e| panic!("ingest {rel}: {e}"));
    Summary {
        objects: report.objects_created,
        watertight: report.watertight,
        leaky: report.leaky,
        skipped: report.skipped.len(),
        materials,
        textured,
        shared_defs,
        textures_missing: report.textures_missing.len(),
    }
}

/// The fidelity the Blender variants must match, model by model. These are the
/// observed-correct numbers for Hew's own export; the round-trip must not lose
/// any of them.
fn expected(name: &str) -> Summary {
    match name {
        "box" => Summary {
            objects: 1,
            watertight: 1,
            leaky: 0,
            skipped: 0,
            materials: 1,
            textured: 0,
            shared_defs: 0,
            textures_missing: 0,
        },
        "instances" => Summary {
            objects: 3,
            watertight: 3,
            leaky: 0,
            skipped: 0,
            materials: 1,
            textured: 0,
            shared_defs: 0,
            textures_missing: 0,
        },
        "countertop" => Summary {
            objects: 8,
            watertight: 8,
            leaky: 0,
            skipped: 0,
            materials: 2,
            textured: 1,
            shared_defs: 0,
            textures_missing: 0,
        },
        other => panic!("no expectation for {other}"),
    }
}

/// Hew's own export imports to the documented baseline (guards the export half +
/// the fidelity numbers the round-trip is measured against).
#[test]
fn hew_export_baseline() {
    for name in ["box", "instances", "countertop"] {
        assert_eq!(
            import_summary(&format!("{name}.glb")),
            expected(name),
            "baseline import of {name}.glb"
        );
    }
}

/// Opening and re-saving in Blender (no edits) loses nothing we track:
/// object/material/texture counts and watertightness all survive.
#[test]
fn blender_passthrough_preserves_fidelity() {
    for name in ["box", "instances", "countertop"] {
        assert_eq!(
            import_summary(&format!("{name}.blender.glb")),
            expected(name),
            "Blender passthrough of {name}"
        );
    }
}

/// A realistic Blender edit (move + 45° rotate, transform applied) re-imports as
/// the same set of watertight Objects — geometry moves, topology/fidelity hold.
#[test]
fn blender_edit_preserves_fidelity() {
    for name in ["box", "instances", "countertop"] {
        assert_eq!(
            import_summary(&format!("{name}.edited.glb")),
            expected(name),
            "Blender edit of {name}"
        );
    }
}

/// Diagnostic dump of every fixture flavour. Run with
/// `cargo test -p gltf-import --test roundtrip report -- --nocapture --ignored`.
#[test]
#[ignore = "diagnostic; prints rather than asserts"]
fn report() {
    for name in ["box", "instances", "countertop"] {
        println!("\n=== {name} ===");
        for variant in ["glb", "blender.glb", "edited.glb"] {
            let s = import_summary(&format!("{name}.{variant}"));
            println!("  {variant:12} {s:?}");
        }
    }
}
