/**
 * WelcomeScreen — the launch dialog for a bare start: no file-association
 * open pending, no crash recovery to offer, primary window only (App.tsx's
 * startup-handoff effect owns that gating; this component only renders).
 *
 * Offers the three ways into the app — start modeling in the already-open
 * blank document, open a file (recents listed when the shell provides
 * them), or load a bundled sample — plus a link to the getting-started
 * guide and a "show on startup" toggle persisted by
 * `settings/welcomeScreen.ts`.
 *
 * Styling follows the RecoveryDialog / ExportDialog family: theme tokens
 * with the same dark fallbacks. Escape and the overlay click both close
 * into the blank document.
 */

import { useEffect, useCallback } from 'react'

/** One bundled sample: the asset file under `samples/` plus display copy. */
export interface SampleEntry {
  file: string
  title: string
  description: string
}

/** The bundled samples (assets in `app/public/samples/`, generated by
 * `cargo run -p kernel --example build_samples`). */
export const BUNDLED_SAMPLES: SampleEntry[] = [
  {
    file: 'pen-cup.hew',
    title: 'Pen Cup',
    description: 'A finished, printable object — export it to STL or 3MF and slice it.',
  },
  {
    file: 'side-table.hew',
    title: 'Side Table',
    description: 'A scene mid-construction: groups, components, materials, and guides.',
  },
]

/** The hosted getting-started guide. */
export const GETTING_STARTED_URL = 'https://hew3d.com/learn/getting-started/'

interface WelcomeScreenProps {
  /** Recent file paths, newest first (empty on the web build). */
  recentFiles: string[]
  /** Close into the blank document ("Start modeling", Escape, overlay). */
  onClose: () => void
  /** Open the file picker. */
  onOpen: () => void
  /** Open one of the recent paths. */
  onOpenRecent: (path: string) => void
  /** Load a bundled sample. */
  onOpenSample: (sample: SampleEntry) => void
  /** Current "show on startup" value. */
  showOnStartup: boolean
  /** Persist a new "show on startup" value. */
  onShowOnStartupChange: (show: boolean) => void
}

const OVERLAY_STYLE: React.CSSProperties = {
  position: 'fixed',
  inset: 0,
  background: 'var(--backdrop-dim, rgba(0,0,0,0.6))',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 2000,
}

const DIALOG_STYLE: React.CSSProperties = {
  background: 'var(--surface-overlay, #2a2a2a)',
  border: '1px solid var(--border-strong, #4a4a4a)',
  borderRadius: 'var(--radius-control, 6px)',
  boxShadow: 'var(--shadow-palette, 0 8px 32px rgba(0,0,0,0.6))',
  padding: '24px 28px',
  width: 'min(560px, calc(100vw - 48px))',
  fontFamily: 'var(--font-family-ui, system-ui, sans-serif)',
  color: 'var(--text-secondary, #ddd)',
}

const HEADING_STYLE: React.CSSProperties = {
  fontSize: '18px',
  fontWeight: 600,
  color: 'var(--text-primary, #eee)',
  marginBottom: '4px',
}

const TAGLINE_STYLE: React.CSSProperties = {
  fontSize: 'var(--font-size-body, 13px)',
  color: 'var(--text-faint, #999)',
  marginBottom: '18px',
}

const SECTION_LABEL_STYLE: React.CSSProperties = {
  fontSize: '11px',
  fontWeight: 600,
  letterSpacing: '0.06em',
  textTransform: 'uppercase',
  color: 'var(--text-section, #888)',
  margin: '14px 0 6px',
}

const CARD_STYLE: React.CSSProperties = {
  display: 'block',
  width: '100%',
  textAlign: 'left',
  padding: '10px 12px',
  background: 'var(--surface-input, #333)',
  color: 'var(--text-primary, #eee)',
  border: '1px solid var(--border-hairline, #444)',
  borderRadius: 'var(--radius-control, 4px)',
  fontSize: 'var(--font-size-body, 13px)',
  fontFamily: 'var(--font-family-ui, system-ui, sans-serif)',
  cursor: 'pointer',
  marginBottom: '6px',
}

const CARD_DESC_STYLE: React.CSSProperties = {
  display: 'block',
  marginTop: '2px',
  fontSize: '12px',
  color: 'var(--text-faint, #999)',
}

const RECENT_STYLE: React.CSSProperties = {
  ...CARD_STYLE,
  padding: '6px 12px',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
}

const FOOTER_STYLE: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '12px',
  marginTop: '18px',
}

const PRIMARY_BUTTON_STYLE: React.CSSProperties = {
  padding: '7px 22px',
  background: 'var(--accent-base, #3a5e9e)',
  color: 'var(--accent-text-strong, #fff)',
  border: 'none',
  borderRadius: 'var(--radius-control, 4px)',
  fontSize: 'var(--font-size-menu-item, 13px)',
  fontFamily: 'var(--font-family-ui, system-ui, sans-serif)',
  cursor: 'pointer',
  marginLeft: 'auto',
}

const LINK_STYLE: React.CSSProperties = {
  color: 'var(--accent-base, #6b9bd8)',
  fontSize: 'var(--font-size-body, 13px)',
  textDecoration: 'none',
}

const CHECKBOX_LABEL_STYLE: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '6px',
  fontSize: '12px',
  color: 'var(--text-faint, #999)',
  cursor: 'pointer',
}

/** The display name of a recent path — its basename, either separator. */
function basename(path: string): string {
  return path.split(/[\\/]/).pop() ?? path
}

export function WelcomeScreen({
  recentFiles,
  onClose,
  onOpen,
  onOpenRecent,
  onOpenSample,
  showOnStartup,
  onShowOnStartupChange,
}: WelcomeScreenProps) {
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault()
        onClose()
      }
    },
    [onClose],
  )

  useEffect(() => {
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [handleKeyDown])

  return (
    <div style={OVERLAY_STYLE} onClick={onClose}>
      <div
        style={DIALOG_STYLE}
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        aria-label="Welcome to Hew"
      >
        <div style={HEADING_STYLE}>Welcome to Hew</div>
        <div style={TAGLINE_STYLE}>
          Draw a profile, push/pull it into a solid, and export a file your slicer accepts —
          no repair step.
        </div>

        <div style={SECTION_LABEL_STYLE}>Sample models</div>
        {BUNDLED_SAMPLES.map((s) => (
          <button key={s.file} style={CARD_STYLE} onClick={() => onOpenSample(s)}>
            {s.title}
            <span style={CARD_DESC_STYLE}>{s.description}</span>
          </button>
        ))}

        {recentFiles.length > 0 && (
          <>
            <div style={SECTION_LABEL_STYLE}>Recent</div>
            {recentFiles.slice(0, 5).map((path) => (
              <button
                key={path}
                style={RECENT_STYLE}
                title={path}
                onClick={() => onOpenRecent(path)}
              >
                {basename(path)}
              </button>
            ))}
          </>
        )}

        <div style={SECTION_LABEL_STYLE}>Or</div>
        <button style={CARD_STYLE} onClick={onOpen}>
          Open a file…
          <span style={CARD_DESC_STYLE}>.hew, or import SketchUp, COLLADA, and glTF.</span>
        </button>

        <div style={FOOTER_STYLE}>
          <a
            style={LINK_STYLE}
            href={GETTING_STARTED_URL}
            target="_blank"
            rel="noreferrer"
          >
            Getting-started guide
          </a>
          <label style={CHECKBOX_LABEL_STYLE}>
            <input
              type="checkbox"
              checked={showOnStartup}
              onChange={(e) => onShowOnStartupChange(e.target.checked)}
            />
            Show on startup
          </label>
          <button style={PRIMARY_BUTTON_STYLE} onClick={onClose} autoFocus>
            Start modeling
          </button>
        </div>
      </div>
    </div>
  )
}
